repos:
  - repo: local
    hooks:
      - id: typecheck
        name: TypeScript type check
        entry: bunx tsc --noEmit
        language: system
        pass_filenames: false
        
      - id: eslint
        name: ESLint
        entry: bunx eslint
        language: system
        types: [file]
        files: \.[jt]sx?$  # *.js, *.ts, *.jsx, *.tsx
